//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Cliente1 = new HashSet<Cliente>();
            this.Tarjeta = new HashSet<Tarjeta>();
        }
    
        public int CUIT { get; set; }
        public Nullable<int> DniConyuge { get; set; }
        public string Domicilio { get; set; }
        public int EstadoCivil { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public Nullable<int> IngresoMesualAprox { get; set; }
        public string Nombre { get; set; }
        public int DNI { get; set; }
        public int Sexo { get; set; }
        public int SituacionLaboral { get; set; }
        public int TipoDocumento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cliente> Cliente1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tarjeta> Tarjeta { get; set; }
    }
}
