//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoSolicitudTarjetas
    {
        public int IdTerminal { get; set; }
        public int NumTarjeta { get; set; }
        public int IdImpresora { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public int EstadoTarjeta { get; set; }
    
        public virtual Impresora Impresora { get; set; }
        public virtual Tarjeta Tarjeta { get; set; }
        public virtual Terminal Terminal { get; set; }
    }
}
