//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjeta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tarjeta()
        {
            this.HistoricoSolicitudTarjetas = new HashSet<HistoricoSolicitudTarjetas>();
            this.Tarjeta1 = new HashSet<Tarjeta>();
        }
    
        public int Numero { get; set; }
        public int Marca { get; set; }
        public int SaldoMaximo { get; set; }
        public int Tipo { get; set; }
        public Nullable<int> Extension { get; set; }
        public int DNICliente { get; set; }
        public int Estado { get; set; }
        public Nullable<int> IdTerminalImpresion { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoricoSolicitudTarjetas> HistoricoSolicitudTarjetas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tarjeta> Tarjeta1 { get; set; }
        public virtual Tarjeta Tarjeta2 { get; set; }
    }
}
