//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terminal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Terminal()
        {
            this.HistoricoSolicitudTarjetas = new HashSet<HistoricoSolicitudTarjetas>();
        }
    
        public int CodigoTerminal { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdImpresora { get; set; }
        public Nullable<int> DNIEmpleado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Impresora Impresora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoricoSolicitudTarjetas> HistoricoSolicitudTarjetas { get; set; }
    }
}
