///////////////////////////////////////////////////////////
//  Empleado.cs
//  Implementation of the Class Empleado
//  Generated by Enterprise Architect
//  Created on:      17-abr-2017 10:09:18
//  Original author: arigos
///////////////////////////////////////////////////////////




namespace BIZ {
	public class Empleado {


		public Empleado(){

		}

		~Empleado(){

		}

	}//end Empleado

}//end namespace BIZ