///////////////////////////////////////////////////////////
//  Empleado.cs
//  Implementation of the Class Empleado
//  Generated by Enterprise Architect
//  Created on:      12-abr-2017 16:59:43
//  Original author: arigos
///////////////////////////////////////////////////////////




using BIZ;
namespace BIZ {
	public class Empleado {

		public Empleado(){

		}

		~Empleado(){

		}

	}//end Empleado

}//end namespace BIZ