///////////////////////////////////////////////////////////
//  EstadoTarjeta.cs
//  Implementation of the Class EstadoTarjeta
//  Generated by Enterprise Architect
//  Created on:      12-abr-2017 16:59:43
//  Original author: arigos
///////////////////////////////////////////////////////////




namespace BIZ {
	public enum EstadoTarjeta : int {

		Emitida,
		Pendiente,
		Impresa

	}//end EstadoTarjeta

}//end namespace BIZ