///////////////////////////////////////////////////////////
//  EstadoCliente.cs
//  Implementation of the Enumeration EstadoCliente
//  Generated by Enterprise Architect
//  Created on:      12-abr-2017 17:01:52
//  Original author: arigos
///////////////////////////////////////////////////////////




using BIZ;
namespace BIZ {
	public enum EstadoCliente : int {

		SinAntecedentes_Bancarios_Crediticios,
		SinAntecedentes_Negativos_Sistema_Financiero,
		Rechazado_ConAntecedentes_Negativos,
		Dudoso,
		Rechazado_SistemasCentralesBanco,
		

	}//end EstadoCliente

}//end namespace BIZ