///////////////////////////////////////////////////////////
//  SolicitudTarjetaFactory.cs
//  Implementation of the Class SolicitudesFactory
//  Generated by Enterprise Architect
//  Created on:      12-abr-2017 16:59:43
//  Original author: arigos
///////////////////////////////////////////////////////////




using BIZ;
namespace BIZ {
	public class SolicitudesFactory {

		public SolicitudesFactory(){

		}

		~SolicitudesFactory(){

		}

		/// 
		/// <param name="nuevoCliente"></param>
		public Cliente CrearNuevoCliente(Cliente nuevoCliente){

			return null;
		}

		/// 
		/// <param name="TarjetaTitular"></param>
		/// <param name="extendido"></param>
		public Tarjeta CrearTarjetaExtension(Tarjeta TarjetaTitular, Cliente extendido){

			return null;
		}

		/// 
		/// <param name="cliente"></param>
		public Tarjeta CrearTarjetaTitular(Cliente cliente){

			return null;
		}

	}//end SolicitudesFactory

}//end namespace BIZ