///////////////////////////////////////////////////////////
//  Empleado.cs
//  Implementation of the Class Empleado
//  Generated by Enterprise Architect
//  Created on:      08-may-2017 14:40:37
//  Original author: arigos
///////////////////////////////////////////////////////////




namespace BIZ {
	public class Empleado {

		public Empleado(){

		}

		~Empleado(){

		}

	}//end Empleado

}//end namespace BIZ