///////////////////////////////////////////////////////////
//  EstadoTarjeta.cs
//  Implementation of the Class EstadoTarjeta
//  Generated by Enterprise Architect
//  Created on:      17-abr-2017 10:09:18
//  Original author: arigos
///////////////////////////////////////////////////////////




namespace BIZ {
	public enum EstadoTarjeta : int {

		Emitida,
		Pendiente,
		Impresa

	}//end EstadoTarjeta

}//end namespace BIZ