///////////////////////////////////////////////////////////
//  EstadoTarjeta.cs
//  Implementation of the Class EstadoTarjeta
//  Generated by Enterprise Architect
//  Created on:      08-may-2017 14:40:37
//  Original author: arigos
///////////////////////////////////////////////////////////




namespace BIZ {
	public enum EstadoTarjeta : int {

		Emitida,
		Pendiente,
		Impresa

	}//end EstadoTarjeta

}//end namespace BIZ