///////////////////////////////////////////////////////////
//  Terminal.cs
//  Implementation of the Class Terminal
//  Generated by Enterprise Architect
//  Created on:      08-may-2017 14:40:37
//  Original author: arigos
///////////////////////////////////////////////////////////




using BIZ;
namespace BIZ {
	/// <summary>
	/// Pc de escritorio de la sucursal donde se va a realizar la impresion de las
	/// tarjetas.
	/// </summary>
	public class Terminal {

		private string _Ciudad;
		public string _Descripcion;
		public BIZ.Empleado m_Empleado;
		public BIZ.ImpresoraSingleton m_ImpresoraSingleton;

		public Terminal(){

		}

		~Terminal(){

		}

		public string Ciudad{
			get{
				return _Ciudad;
			}
			set{
				_Ciudad = value;
			}
		}

		public string Descripcion{
			get{
				return _Descripcion;
			}
			set{
				_Descripcion = value;
			}
		}

		/// 
		/// <param name="tajetaImprimir"></param>
		public void ImprimirTarjeta(Tarjeta tajetaImprimir){

		}

	}//end Terminal

}//end namespace BIZ